build:
  build_starting:
        image: python:2
        commands:
            - echo "Beginning new build"
  run_tests:
    image: python:2-alpine
    commands:
      - pip install -r requirements.txt
      - python tests.py

publish:
  docker:
    repo: $$DOCKER_USERNAME/$$DOCKER_REPO
    tag: latest
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL

deploy:
  webhook:
    image: plugins/drone-webhook
    urls:
      - https://$$MARATHON/marathon/v2/apps/$$APPNAME/restart
